$(document).ready(function() {
    var menuLink = ' <li><a href="https://grcodeclub.github.io">Αρχική Σελίδα</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/linux/">Linux</li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = ' <li><a href="https://grcodeclub.github.io/system/">Λειτουργικό Σύστημα</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/linux/post/cmd/network.html">Εντολές Δικτύου</li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/linux/post/cmd/system.html">Εντολές Συστήματος</li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/linux/post/cmd/file.html">Eντολές Διαχείρισης Αρχείων και Καταλόγων</li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/linux/post/system_file.html">Αρχεία</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/windows">Windows</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li style="height: 200px;"></li>';
    $('.sidebarMenuInner').append(menuLink);
  });
